In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("clean_data.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        621 non-null    object
 1   company     621 non-null    object
 2   year        621 non-null    int64
 3   Price       621 non-null    float64
 4   kms_driven  621 non-null    float64
 5   fuel_type   621 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 29.2+ KB

In [5]:
len(df['name'].unique())

402

In [6]:
len(df['company'].unique())

25

In [23]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [24]:
ohe = OneHotEncoder()

In [25]:
ohe.fit(df[['name','company','fuel_type']])

OneHotEncoder()

In [26]:
ohe.categories_

[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
        '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
        'A4 1.8 TFSI Multitronic Premium Plus',
        'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8',
        'Accent Executive Edition', 'Accord', 'Amaze',
        'Amaze 1.2 S i VTEC', 'Amaze 1.2 VX i VTEC', 'Amaze 1.5 E i DTEC',
        'Amaze 1.5 S i DTEC', 'Amaze 1.5 SX i DTEC', 'Aria Pleasure 4X2',
        'Beat', 'Beat Diesel', 'Beat LS Diesel', 'Beat LS Petrol',
        'Beat LT Diesel', 'Beat LT Opt Diesel', 'Beat LT Petrol',
        'Beat PS Diesel', 'Benz A Class A 180 Sport Petrol',
        'Benz B Class B180 Sports', 'Benz C Class 200 CDI Classic',
        'Benz C Class 200 K MT', 'Benz C Class C 220 CDI Avantgarde',
        'Benz GLA Class 200 CDI Sport', 'Bolero DI', 'Bolero DI BSII',
        'Bolero Power Plus SLE', 'Bolero SLE BS IV', 'Bolt XM Petrol',
        'Brio', 'Brio V MT', 'Brio VX AT', 'City', 'City 1.5 EXi New',
        'City 1.5 S Inspire', 'City 1.5 S MT', 'City 1.5 V AT',
        'City 1.5 V MT', 'City 1.5 V MT Exclusive', 'City SV',
        'City VX O MT Diesel', 'City VX Petrol', 'City ZX CVT',
        'City ZX EXi', 'City ZX GXi', 'City ZX VTEC', 'Cooper S',
        'Cooper S 1.6', 'Corolla', 'Corolla Altis', 'Corolla Altis 1.8 GL',
        'Corolla Altis 1.8 J', 'Corolla Altis Diesel D4DG',
        'Corolla Altis GL Petrol', 'Corolla Altis Petrol Ltd',
        'Corolla Altis VL AT Petrol', 'Corolla H2', 'Creta',
        'Creta 1.6 SX Plus Petrol', 'Creta 1.6 SX Plus Petrol AT',
        'Cruze LTZ', 'Cruze LTZ AT', 'Duster', 'Duster 110 PS RxL Diesel',
        'Duster 110 PS RxZ Diesel', 'Duster 110 PS RxZ Diesel Plus',
        'Duster 110PS Diesel RxZ', 'Duster 85 PS RxE Diesel',
        'Duster 85 PS RxL Diesel', 'Duster 85 PS RxL Explore LE',
        'Duster 85PS Diesel RxL Optional with Nav', 'Duster RxL Petrol',
        'EcoSport', 'EcoSport Ambiente 1.5L TDCi',
        'EcoSport Titanium 1.5 TDCi', 'EcoSport Titanium 1.5L TDCi',
        'EcoSport Trend 1.5 Ti VCT', 'EcoSport Trend 1.5L TDCi',
        'EcoSport Trend 1.5L Ti VCT', 'Elantra 1.8 S', 'Elantra SX',
        'Elite i20', 'Elite i20 Asta 1.2', 'Elite i20 Asta 1.4 CRDI',
        'Elite i20 Magna 1.2', 'Elite i20 Sportz 1.2',
        'Endeavor 4x4 Thunder Plus', 'Enjoy', 'Enjoy 1.4 LS 8 STR', 'Eon',
        'Eon D Lite Plus', 'Eon Era Plus', 'Eon Magna', 'Eon Magna Plus',
        'Eon Sportz', 'Etios', 'Etios G', 'Etios GD', 'Etios Liva',
        'Etios Liva Diesel', 'Etios Liva G', 'Etios Liva GD', 'Fabia',
        'Fabia 1.2L Diesel Ambiente', 'Fabia 1.2L Diesel Elegance',
        'Fabia Classic 1.2 MPI', 'Fiesta', 'Fiesta SXi 1.6 ABS', 'Figo',
        'Figo Diesel EXI', 'Figo Diesel EXI Option',
        'Figo Duratorq Diesel Titanium 1.4', 'Figo Petrol LXI',
        'Fluidic Verna 1.6 CRDi SX', 'Fortuner', 'Fortuner 3.0 4x2 MT',
        'Fortuner 3.0 4x4 MT', 'Fusion 1.4 TDCi Diesel', 'GO T O', 'Getz',
        'Getz Prime 1.3 GLX', 'Getz Prime 1.3 GVS', 'Go Plus', 'Grand i10',
        'Grand i10 Asta 1.1 CRDi', 'Grand i10 Asta 1.2 Kappa VTVT',
        'Grand i10 Asta 1.2 Kappa VTVT O',
        'Grand i10 Magna 1.2 Kappa VTVT',
        'Grand i10 Magna AT 1.2 Kappa VTVT',
        'Grand i10 Sportz 1.2 Kappa VTVT',
        'Grand i10 Sportz O 1.2 Kappa VTVT', 'Indica V2 DLE BS III',
        'Indica V2 LS', 'Indica V2 Xeta e GLE', 'Indica eV2 LS',
        'Indigo CS GLS', 'Indigo CS eLS BS IV', 'Indigo CS eLX BS IV',
        'Indigo LS', 'Indigo LX TDI BS III', 'Indigo Marina LS',
        'Indigo eCS', 'Indigo eCS LS CR4 BS IV', 'Indigo eCS LX CR4 BS IV',
        'Indigo eCS LX TDI BS III', 'Indigo eCS VX CR4 BS IV',
        'Innova 2.0 G 8 STR BS IV', 'Innova 2.0 G4', 'Innova 2.5 E 8 STR',
        'Innova 2.5 G BS III 8 STR', 'Innova 2.5 GX BS IV 7 STR',
        'Innova 2.5 V 7 STR', 'Innova 2.5 Z Diesel 7 Seater', 'Jazz S MT',
        'Jazz VX MT', 'Jeep CL550 MDI', 'Jetta Comfortline 1.9 TDI AT',
        'Jetta Highline TDI AT', 'KUV100', 'KUV100 K8 6 STR',
        'KUV100 K8 D 6 STR', 'Kwid', 'Kwid 1.0', 'Kwid 1.0 RXT AMT',
        'Kwid RXT', 'Kwid RXT Opt', 'Laura',
        'Linea Emotion 1.4 L T Jet Petrol', 'Lodgy 85 PS RXL', 'Logan',
        'Logan Diesel 1.5 DLS', 'Manza Aqua Quadrajet',
        'Manza Aura Quadrajet', 'Manza ELAN Quadrajet', 'Micra XL',
        'Micra XV', 'Mobilio', 'Mobilio S i DTEC',
        'Motors  One LX ABS 7 STR',
        'Motors Ambassador Classic Mark 4 – Befo', 'Motors One SUV',
        'Octavia Classic 1.9 TDI MT', 'Pajero Sport 2.5 AT',
        'Pajero Sport Limited Edition', 'Passat Diesel Comfortline AT',
        'Polo', 'Polo Comfortline 1.2L P', 'Polo Highline Exquisite P',
        'Polo Highline1.2L P', 'Polo Trendline 1.5L D',
        'Punto Emotion 1.2', 'Q3 2.0 TDI quattro Premium',
        'Q5 2.0 TDI quattro Premium Plus', 'Q7', 'Qualis', 'Quanto C4',
        'Quanto C8', 'Rapid Elegance 1.6 TDI CR MT', 'Redi GO',
        'Redi GO S', 'Redi GO T O', 'Rover Freelander 2 SE',
        'S80 Summum D4', 'Sail 1.2 LS', 'Sail UVA Petrol LT ABS',
        'Santro AE GLS Audio', 'Santro Xing', 'Santro Xing GLS',
        'Santro Xing XL AT eRLX Euro III', 'Santro Xing XL eRLX Euro III',
        'Scala RxL Diesel', 'Scala RxL Diesel Travelogue', 'Scorpio',
        'Scorpio 2.6 CRDe', 'Scorpio 2.6 SLX', 'Scorpio LX BS III',
        'Scorpio S10', 'Scorpio S10 4WD', 'Scorpio S4',
        'Scorpio SLE BS IV', 'Scorpio SLX', 'Scorpio SLX 2.6 Turbo 8 Str',
        'Scorpio VLX 2.2 mHawk Airbag BSIV', 'Scorpio VLX 2WD BS IV',
        'Scorpio VLX 4WD Airbag', 'Scorpio VLX Airbag',
        'Scorpio VLX Special Edition BS III', 'Scorpio Vlx BSIV',
        'Scorpio W Turbo 2.6DX 9 Seater', 'Sonata Transform 2.4 GDi MT',
        'Spark', 'Spark LS 1.0', 'Spark LT 1.0 Airbag',
        'Sumo Gold EX BS IV', 'Sumo Gold FX BSIII', 'Sumo Gold LX BS IV',
        'Sumo Gold Select Variant', 'Sumo Grande MKII GX',
        'Sumo Victa EX 10 by 7 Str BSIII', 'Sunny', 'Sunny XL',
        'Superb 1.8 TFSI AT', 'Suzuki A Star Lxi', 'Suzuki Alto',
        'Suzuki Alto 800', 'Suzuki Alto 800 Lx', 'Suzuki Alto 800 Lxi',
        'Suzuki Alto 800 Vxi', 'Suzuki Alto AX', 'Suzuki Alto K10 LXi CNG',
        'Suzuki Alto K10 New', 'Suzuki Alto K10 VXi',
        'Suzuki Alto K10 VXi AMT', 'Suzuki Alto K10 VXi AT',
        'Suzuki Alto LXi BS III', 'Suzuki Alto Std BS IV',
        'Suzuki Baleno Delta 1.2', 'Suzuki Baleno Sigma 1.2',
        'Suzuki Baleno Zeta 1.2', 'Suzuki Celerio VDi',
        'Suzuki Ciaz VXi Plus', 'Suzuki Ciaz ZXI Plus',
        'Suzuki Ciaz ZXi Plus RS', 'Suzuki Dzire', 'Suzuki Dzire LDI',
        'Suzuki Dzire VDI', 'Suzuki Dzire ZXI',
        'Suzuki Eeco 5 STR WITH AC HTR', 'Suzuki Eeco 7 STR',
        'Suzuki Ertiga', 'Suzuki Ertiga LDi', 'Suzuki Ertiga VDi',
        'Suzuki Ertiga Vxi', 'Suzuki Ertiga ZXI Plus', 'Suzuki Ertiga ZXi',
        'Suzuki Estilo LX BS IV', 'Suzuki Estilo VXi ABS BS IV',
        'Suzuki Omni', 'Suzuki Omni E 8 STR BS IV',
        'Suzuki Omni LPG BS IV', 'Suzuki Omni Select Variant',
        'Suzuki Ritz', 'Suzuki Ritz GENUS VXI', 'Suzuki Ritz LDi',
        'Suzuki Ritz VDi', 'Suzuki Ritz VXI', 'Suzuki Ritz VXI ABS',
        'Suzuki S Cross Sigma 1.3', 'Suzuki SX4',
        'Suzuki SX4 Celebration Diesel', 'Suzuki SX4 ZXI MT',
        'Suzuki Stingray VXi', 'Suzuki Swift', 'Suzuki Swift Dzire',
        'Suzuki Swift Dzire Tour LDi', 'Suzuki Swift Dzire Tour LXi',
        'Suzuki Swift Dzire Tour VDi', 'Suzuki Swift Dzire VDi',
        'Suzuki Swift Dzire VXi 1.2 BS IV', 'Suzuki Swift Dzire ZDi',
        'Suzuki Swift GLAM', 'Suzuki Swift LDi', 'Suzuki Swift RS VDI',
        'Suzuki Swift Select Variant', 'Suzuki Swift VDi',
        'Suzuki Swift VDi ABS', 'Suzuki Swift VDi BS IV',
        'Suzuki Swift VXI BSIII', 'Suzuki Swift VXi 1.2 ABS BS IV',
        'Suzuki Swift VXi 1.2 BS IV', 'Suzuki Swift Vdi BSIII',
        'Suzuki Swift ZXi 1.2 BS IV', 'Suzuki Vitara Brezza',
        'Suzuki Vitara Brezza LDi O', 'Suzuki Vitara Brezza ZDi',
        'Suzuki Wagon R', 'Suzuki Wagon R 1.0 VXi',
        'Suzuki Wagon R AX BSIV', 'Suzuki Wagon R Duo Lxi',
        'Suzuki Wagon R LXI BS IV', 'Suzuki Wagon R LXi BS III',
        'Suzuki Wagon R Select Variant', 'Suzuki Wagon R VXI BS IV',
        'Suzuki Wagon R VXi BS III', 'Suzuki Wagon R VXi Minor',
        'Suzuki Zen Estilo', 'Suzuki Zen Estilo LXI Green CNG',
        'TUV300 T4 Plus', 'TUV300 T8', 'Tavera LS B3 10 Seats BSII',
        'Tavera Neo', 'Terrano XL D Plus', 'Thar CRDe 4x4 AC',
        'Tiago Revotron XM', 'Tiago Revotron XZ',
        'Vento Comfortline Diesel', 'Vento Comfortline Petrol',
        'Vento Highline Plus 1.5 Diesel AT',
        'Vento Konekt Diesel Highline', 'Verna', 'Verna 1.4 VTVT',
        'Verna 1.6 CRDI E', 'Verna 1.6 CRDI SX',
        'Verna 1.6 CRDI SX Plus AT', 'Verna 1.6 EX VTVT',
        'Verna 1.6 SX VTVT AT', 'Verna Fluidic',
        'Verna Fluidic 1.6 VTVT SX', 'Verna Fluidic New',
        'Verna Transform SX VTVT', 'Verna VGT CRDi SX ABS',
        'Vista Quadrajet VX', 'WR V S MT Petrol',
        'Wrangler Unlimited 4x4 Diesel', 'X1', 'X1 sDrive20d',
        'X1 xDrive20d xLine', 'XE XE Portfolio', 'XF 2.2 Diesel Luxury',
        'XUV500', 'XUV500 W10', 'XUV500 W6', 'XUV500 W8',
        'XUV500 W8 AWD 2013', 'Xcent Base 1.1 CRDi', 'Xcent SX 1.2',
        'Xylo D2', 'Xylo D2 BS IV', 'Xylo E4', 'Xylo E8', 'Xylo E8 BS IV',
        'Yeti Ambition 2.0 TDI CR 4x2', 'Zest Quadrajet 1.3',
        'Zest XE 75 PS Diesel', 'Zest XM Diesel', 'i10', 'i10 Era',
        'i10 Magna 1.2', 'i10 Magna 1.2 Kappa2', 'i10 Sportz',
        'i10 Sportz 1.2', 'i20', 'i20 Active', 'i20 Active 1.2 SX',
        'i20 Active 1.4L SX O', 'i20 Asta', 'i20 Asta 1.2',
        'i20 Asta 1.4 CRDI 6 Speed', 'i20 Magna', 'i20 Magna 1.2',
        'i20 Magna O 1.2', 'i20 Select Variant', 'i20 Sportz 1.4 CRDI'],
       dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [28]:
ct =make_column_transformer((OneHotEncoder(categories=ohe.categories_),["name","company","fuel_type"]),remainder="passthrough")

In [30]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8',
       'Accent Executive Edition', 'Accord', 'Amaze',
       'Amaze 1.2 S i VTEC...
       'i20 Magna O 1.2', 'i20 Select Variant', 'i20 Sportz 1.4 CRDI'],
      dtype=object),
                                                           array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                           array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'company', 'fuel_type'])])

In [31]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [32]:
from sklearn.pipeline import make_pipeline

In [33]:
pipe = make_pipeline(ct,reg)

In [35]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8',
       'Accent Executive Edit...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [36]:
from sklearn.model_selection import train_test_split

In [38]:
df.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='object')

In [40]:
X= df[['name', 'company', 'year',  'kms_driven', 'fuel_type']]
X

                               name   company  year  kms_driven fuel_type
0    Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014     28000.0    Petrol
1       EcoSport Titanium 1.5L TDCi      Ford  2014     36000.0    Diesel
2                              Figo      Ford  2012     41000.0    Diesel
3                               Eon   Hyundai  2013     25000.0    Petrol
4       EcoSport Ambiente 1.5L TDCi      Ford  2016     24530.0    Diesel
..                              ...       ...   ...         ...       ...
616             Suzuki Ritz VXI ABS    Maruti  2011     50000.0    Petrol
617            Indica V2 DLE BS III      Tata  2009     30000.0    Diesel
618                   Corolla Altis    Toyota  2009    132000.0    Petrol
619                  Zest XM Diesel      Tata  2018     27000.0    Diesel
620                       Quanto C8  Mahindra  2013     40000.0    Diesel

[621 rows x 5 columns]

In [41]:
y = df[['Price']]
y

        Price
0    325000.0
1    575000.0
2    175000.0
3    190000.0
4    830000.0
..        ...
616  270000.0
617  110000.0
618  300000.0
619  260000.0
620  390000.0

[621 rows x 1 columns]

In [42]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=0)

In [43]:
X_train

                               name   company  year  kms_driven fuel_type
298                        Kwid RXT   Renault  2015     43000.0    Petrol
575                     Suzuki Ritz    Maruti  2010     38000.0    Diesel
8               Elite i20 Magna 1.2   Hyundai  2014     32000.0    Petrol
414                    Xcent SX 1.2   Hyundai  2015     43000.0    Diesel
441              Innova 2.5 V 7 STR    Toyota  2011    147000.0    Diesel
..                              ...       ...   ...         ...       ...
277  Scorpio W Turbo 2.6DX 9 Seater  Mahindra  2012     65000.0    Diesel
9                 Scorpio SLE BS IV  Mahindra  2015     48660.0    Diesel
359   Suzuki Eeco 5 STR WITH AC HTR    Maruti  2015     39000.0    Petrol
192                Suzuki Dzire ZXI    Maruti  2013     30000.0    Petrol
559                Suzuki Swift VDi    Maruti  2011     58000.0    Diesel

[558 rows x 5 columns]

In [44]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series 320d Sedan', '3 Series 320i', '5 Series 520d Sedan',
       '5 Series 530i', '7 Series 740Li Sedan', 'A3 Cabriolet 40 TFSI',
       'A4 1.8 TFSI Multitronic Premium Plus',
       'A4 2.0 TDI 177bhp Premium', 'A6 2.0 TDI Premium', 'A8',
       'Accent Executive Edit...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [51]:
input = pd.DataFrame(data=[['Grand i10 Magna 1.2 Kappa VTVT','Hyundai',2015,30000,'Diesel']],columns=['name', 'company', 'year',  'kms_driven', 'fuel_type'])

In [52]:
input

                             name  company  year  kms_driven fuel_type
0  Grand i10 Magna 1.2 Kappa VTVT  Hyundai  2015       30000    Diesel

In [53]:
pipe.predict(input)

array([[435268.86812328]])

In [57]:
ypred = pipe.predict(X_test)
ypred = pd.DataFrame(data=ypred,columns=['Result'])
ypred

          Result
0   8.128266e+05
1   2.847415e+05
2   3.226462e+05
3   3.498621e+05
4   5.284880e+05
..           ...
58  3.313142e+05
59  4.907599e+05
60  1.753913e+05
61  1.252824e+06
62  2.601123e+05

[63 rows x 1 columns]

In [58]:
y_test

         Price
389  1299000.0
458   500000.0
436   260000.0
367   350000.0
375   900000.0
..         ...
170   340000.0
333   399000.0
558   130000.0
496  1000000.0
366   180000.0

[63 rows x 1 columns]

In [60]:
result = pd.concat([y_test.reset_index(drop= True),ypred.reset_index(drop= True)],axis=1)
result

        Price        Result
0   1299000.0  8.128266e+05
1    500000.0  2.847415e+05
2    260000.0  3.226462e+05
3    350000.0  3.498621e+05
4    900000.0  5.284880e+05
..        ...           ...
58   340000.0  3.313142e+05
59   399000.0  4.907599e+05
60   130000.0  1.753913e+05
61  1000000.0  1.252824e+06
62   180000.0  2.601123e+05

[63 rows x 2 columns]

In [61]:
from sklearn.metrics import r2_score
score = r2_score(result['Price'],result['Result'])
score

0.5298330957083263

In [68]:
arr =[]
for i in range(0,101):
    X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=i)
    pipe.fit(X_train,y_train)
    ypred = pipe.predict(X_test)
    ypred = pd.DataFrame(data=ypred,columns=['Result'])
    result = pd.concat([y_test.reset_index(drop= True),ypred.reset_index(drop= True)],axis=1)
    score = r2_score(result['Price'],result['Result'])
    arr.append(score)

In [69]:
arr

[0.5298330957083263,
 0.7611698447234925,
 0.678953890926631,
 0.19771985901961153,
 0.1143667916309209,
 0.4661458248237319,
 0.35735324892231735,
 0.712457607059443,
 0.7325610883115419,
 0.7398767764071085,
 0.3498632589131836,
 0.5503242574630924,
 0.2802162251059287,
 0.4059057386054372,
 0.4331769779073168,
 0.49894839936000823,
 0.7087235955151518,
 0.6465177294724198,
 0.6233075398505887,
 0.6685889967719878,
 0.6037184515275602,
 0.5857817362445106,
 0.6083849634039005,
 0.7010506226595247,
 0.3494295239719253,
 0.5185444065016831,
 0.6900018903387355,
 0.5523176344809264,
 0.5101894957318787,
 0.6258038680594862,
 0.6970605830784791,
 0.568781477105615,
 0.5443407840259116,
 0.34383055260176654,
 0.7428850772857859,
 0.44963267208659763,
 0.43009796527203414,
 0.5710342180556148,
 0.34042720168045315,
 0.5410464578427705,
 0.39061843754128567,
 0.593865430147151,
 0.22035176737111906,
 0.5502437548370833,
 0.6492844816036618,
 0.5926737261080994,
 0.4733305691294212,
 0.5800049168623003,
 0.5071434454471457,
 0.5694178705984037,
 0.35170533593340547,
 0.5039049321325398,
 0.4654873970213911,
 0.5321588637825321,
 0.5662588440022983,
 0.689910802714423,
 0.5381846357310542,
 0.19487617049843076,
 0.5447172753079788,
 0.414966541863362,
 0.5865719229882448,
 0.6255769467330939,
 0.7121496489227488,
 -0.015195991996174829,
 0.5287580019481584,
 0.5992073625709047,
 0.744988537821114,
 0.6324116337167051,
 0.5537585632243371,
 0.216681482489539,
 0.5458063346811003,
 0.5142685130383824,
 0.5321517052864404,
 0.5398673747274534,
 0.7131756085905214,
 0.40772470766182445,
 0.6637049425374425,
 0.3760635350534648,
 0.7469568441419563,
 0.360186989681755,
 0.21187761222468815,
 0.5666733300139601,
 0.46530432818188017,
 0.4846525970322966,
 0.4465540642546866,
 0.7031890153790569,
 0.32299434969772556,
 0.36834027958466553,
 0.6840782993899341,
 0.41754673902813755,
 0.792668160101959,
 0.6949142776001891,
 0.6534028821727114,
 0.67758681581003,
 -0.1636508631788398,
 0.3846269305376244,
 0.6468124141181859,
 0.5100679332050695,
 0.45109236989463963,
 0.46536728089285595,
 0.5760122647917482]

In [70]:
index = np.argmax(arr)
index

np.int64(90)

In [72]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.1,random_state=90)
pipe.fit(X_train,y_train)
ypred = pipe.predict(X_test)
ypred = pd.DataFrame(data=ypred,columns=['Result'])
result = pd.concat([y_test.reset_index(drop= True),ypred.reset_index(drop= True)],axis=1)
score = r2_score(result['Price'],result['Result'])
score*100

79.2668160101959

In [73]:
import pickle as pkl

In [74]:
pkl.dump(pipe,open("CPP.pkl","wb+"))